FROM node:16-bullseye as build-stage

WORKDIR ./

COPY ./client/package*.json ./
RUN npm install

COPY ./client ./
RUN npm run build

COPY ./client ./

FROM nginx:1.13.12-alpine as production-stage

COPY --from=build-stage ./build /var/www/html/

EXPOSE $PORT

COPY ./client/nginx.conf /etc/nginx/nginx.conf

COPY ./client/nginx.vh.default.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
