FROM node:16-bullseye

ENV HOME_DIR /home/app
ENV API_DIR $HOME_DIR/crm_server
ENV LIB_DIR $API_DIR/lib

ENV TZ=Europe/Kiev

RUN apt-get update -y && \
    apt-get install -yq tzdata && \
    ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

COPY ./server $API_DIR
COPY ./lib/dist/* $LIB_DIR

RUN rm $LIB_DIR/index.d.ts

WORKDIR $API_DIR

COPY package*.json ./
RUN npm install
RUN npm run build

EXPOSE $PORT

CMD ["npm", "run" ,"start:prod"]
